#!/bin/bash
# ─────────────────────────────────────────
# MODULE: report.sh
# Generates .txt and .html reports
# ─────────────────────────────────────────

generate_report() {
    local report_dir="$1"
    local filename_base
    filename_base="${report_dir}/PhishReport_$(date +%Y%m%d_%H%M%S)"

    local txt_file="${filename_base}.txt"
    local html_file="${filename_base}.html"

    # ── Build auto summary paragraph ──────────────────────────────────────────
    local summary
    summary="On ${SCAN_DATE}, analyst ${ANALYST_NAME} examined a file named '${SAMPLE_FILENAME}' "
    summary+="(${FILE_SIZE}, type: ${FILE_TYPE}) received via ${SOURCE_LABEL}. "

    if [[ -n "$SENDER_EMAIL" ]]; then
        summary+="The file was sent from ${SENDER_EMAIL}"
        [[ -n "$EMAIL_SUBJECT" ]] && summary+=" with subject line: '${EMAIL_SUBJECT}'"
        summary+=". "
    fi

    summary+="Static analysis identified a risk level of ${STATIC_RISK}. "
    summary+="VirusTotal returned a verdict of ${VT_VERDICT} "
    summary+="(${VT_ENGINES_FLAGGED}/${VT_ENGINES_TOTAL} engines flagged"
    [[ "$VT_MALWARE_NAME" != "Unknown" ]] && summary+=", classified as ${VT_MALWARE_NAME}"
    summary+="). "

    if [[ "$VT_VERDICT" == "MALICIOUS" || "$VT_VERDICT" == "SUSPICIOUS" ]]; then
        summary+="Immediate isolation and incident response is recommended."
    else
        summary+="Continue monitoring and apply standard precautionary measures."
    fi

    # ── Determine overall risk colour ─────────────────────────────────────────
    local risk_color risk_bg
    case "$VT_VERDICT" in
        MALICIOUS)   risk_color="#c0392b"; risk_bg="#fadbd8" ;;
        SUSPICIOUS)  risk_color="#d35400"; risk_bg="#fdebd0" ;;
        "LOW RISK")  risk_color="#f39c12"; risk_bg="#fef9e7" ;;
        *)           risk_color="#27ae60"; risk_bg="#eafaf1" ;;
    esac

    # ══════════════════════════════════════════════════════════════════════════
    #  TXT REPORT
    # ══════════════════════════════════════════════════════════════════════════
    cat > "$txt_file" <<EOF
╔══════════════════════════════════════════════════════════════════════╗
║                     P H I S H   R E P O R T                        ║
╚══════════════════════════════════════════════════════════════════════╝
Analyst : $ANALYST_NAME
Date    : $SCAN_DATE
Case ID : PhishReport_$(date +%Y%m%d_%H%M%S)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 1 — WHAT WAS ANALYSED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  File Name     : $SAMPLE_FILENAME
  File Size     : $FILE_SIZE
  File Type     : $FILE_TYPE
  Source        : $SOURCE_LABEL
  Sender Email  : ${SENDER_EMAIL:-"(not provided)"}
  Email Subject : ${EMAIL_SUBJECT:-"(not provided)"}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 2 — STATIC ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  SHA-256  : $HASH_SHA256
  SHA-1    : $HASH_SHA1
  MD5      : $HASH_MD5

  Static Risk Level : $STATIC_RISK

  ── Suspicious Keywords Found ──
${STRINGS_KEYWORDS:-  (none detected)}

  ── URLs Found ──
${STRINGS_URLS:-  (none detected)}

  ── Domains Found ──
${STRINGS_DOMAINS:-  (none detected)}

  ── Email Addresses Found ──
${STRINGS_EMAILS:-  (none detected)}

  ── VirusTotal Results ──
  Engines Flagged : $VT_ENGINES_FLAGGED / $VT_ENGINES_TOTAL
  Malware Name    : $VT_MALWARE_NAME
  First Seen      : $VT_FIRST_SEEN
  Verdict         : $VT_VERDICT
  VT Report Link  : $VT_LINK

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 3 — DYNAMIC ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Hybrid Analysis Sandbox Link:
  https://www.hybrid-analysis.com/search?query=$HASH_SHA256

  ── IP Addresses & GeoIP ──
${GEO_RESULTS:-  (no external IPs found)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 4 — REMEDIATION ACTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  [ ] Isolate the affected machine from the network immediately
  [ ] Preserve and back up forensic evidence (disk image, logs)
  [ ] Block the sender email address at the mail gateway
  [ ] Block identified malicious domains/IPs at the firewall
  [ ] Submit sample to AV vendor for signature update
  [ ] Scan all machines that may have received the same email
  [ ] Reset credentials of any potentially exposed accounts
  [ ] Notify management / CISO per incident response policy
  [ ] Document all actions with timestamps
  [ ] Conduct post-incident review

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECTION 5 — SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  $summary

══════════════════════════════════════════════════════════════════════
  Generated by PhishReport | Analyst: $ANALYST_NAME | $SCAN_DATE
══════════════════════════════════════════════════════════════════════
EOF

    # ══════════════════════════════════════════════════════════════════════════
    #  HTML REPORT
    # ══════════════════════════════════════════════════════════════════════════
    cat > "$html_file" <<HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>PhishReport — ${SAMPLE_FILENAME}</title>
<style>
  :root { --accent: #2c3e50; --danger: ${risk_color}; --danger-bg: ${risk_bg}; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', Arial, sans-serif; background: #f0f2f5; color: #222; }
  .header { background: var(--accent); color: #fff; padding: 28px 40px; }
  .header h1 { font-size: 2rem; letter-spacing: 2px; }
  .header p  { opacity: .7; margin-top: 4px; font-size: .9rem; }
  .verdict-banner { background: var(--danger-bg); border-left: 6px solid var(--danger);
    color: var(--danger); padding: 14px 40px; font-size: 1.2rem; font-weight: bold; }
  .container { max-width: 960px; margin: 30px auto; padding: 0 20px; }
  .section { background: #fff; border-radius: 8px; box-shadow: 0 1px 6px rgba(0,0,0,.08);
    margin-bottom: 24px; overflow: hidden; }
  .section-title { background: var(--accent); color: #fff; padding: 10px 20px;
    font-size: 1rem; font-weight: 600; letter-spacing: 1px; }
  .section-body { padding: 20px; }
  table { width: 100%; border-collapse: collapse; }
  td { padding: 8px 12px; border-bottom: 1px solid #eee; vertical-align: top; }
  td:first-child { width: 200px; color: #555; font-weight: 600; }
  .hash { font-family: monospace; font-size: .85rem; word-break: break-all; color: #27ae60; }
  .tag { display:inline-block; padding:2px 8px; border-radius:12px; font-size:.8rem;
    font-weight:600; background:var(--danger-bg); color:var(--danger); }
  pre { background: #f8f9fa; padding: 14px; border-radius: 6px; font-size:.82rem;
    overflow-x:auto; white-space:pre-wrap; word-break:break-word; color:#333; }
  .checklist li { list-style: none; padding: 6px 0; border-bottom: 1px solid #eee; }
  .checklist li::before { content: "☐  "; color: var(--accent); font-size: 1.1rem; }
  .summary-box { background: var(--danger-bg); border-left: 4px solid var(--danger);
    padding: 16px; border-radius: 4px; line-height: 1.7; }
  .footer { text-align:center; color:#999; font-size:.8rem; padding: 20px; }
  a { color: #2980b9; }
</style>
</head>
<body>

<div class="header">
  <h1>🛡 PhishReport</h1>
  <p>Analyst: ${ANALYST_NAME} &nbsp;|&nbsp; Date: ${SCAN_DATE} &nbsp;|&nbsp; File: ${SAMPLE_FILENAME}</p>
</div>

<div class="verdict-banner">
  ⚠ Verdict: ${VT_VERDICT} &nbsp;|&nbsp; Engines: ${VT_ENGINES_FLAGGED}/${VT_ENGINES_TOTAL} flagged &nbsp;|&nbsp; ${VT_MALWARE_NAME}
</div>

<div class="container">

  <!-- SECTION 1 -->
  <div class="section">
    <div class="section-title">SECTION 1 — WHAT WAS ANALYSED</div>
    <div class="section-body">
      <table>
        <tr><td>File Name</td><td>${SAMPLE_FILENAME}</td></tr>
        <tr><td>File Size</td><td>${FILE_SIZE}</td></tr>
        <tr><td>File Type</td><td>${FILE_TYPE}</td></tr>
        <tr><td>Source</td><td>${SOURCE_LABEL}</td></tr>
        <tr><td>Sender Email</td><td>${SENDER_EMAIL:-<em>(not provided)</em>}</td></tr>
        <tr><td>Email Subject</td><td>${EMAIL_SUBJECT:-<em>(not provided)</em>}</td></tr>
      </table>
    </div>
  </div>

  <!-- SECTION 2 -->
  <div class="section">
    <div class="section-title">SECTION 2 — STATIC ANALYSIS</div>
    <div class="section-body">
      <table>
        <tr><td>SHA-256</td><td class="hash">${HASH_SHA256}</td></tr>
        <tr><td>SHA-1</td><td class="hash">${HASH_SHA1}</td></tr>
        <tr><td>MD5</td><td class="hash">${HASH_MD5}</td></tr>
        <tr><td>Static Risk</td><td><span class="tag">${STATIC_RISK}</span></td></tr>
      </table>
      <br>
      <strong>Suspicious Keywords:</strong>
      <pre>${STRINGS_KEYWORDS:-No suspicious keywords detected.}</pre>
      <strong>URLs Found:</strong>
      <pre>${STRINGS_URLS:-None detected.}</pre>
      <strong>Domains Found:</strong>
      <pre>${STRINGS_DOMAINS:-None detected.}</pre>
      <strong>Emails Found:</strong>
      <pre>${STRINGS_EMAILS:-None detected.}</pre>
      <br>
      <strong>VirusTotal Results:</strong>
      <table>
        <tr><td>Engines Flagged</td><td>${VT_ENGINES_FLAGGED} / ${VT_ENGINES_TOTAL}</td></tr>
        <tr><td>Malware Name</td><td>${VT_MALWARE_NAME}</td></tr>
        <tr><td>First Seen</td><td>${VT_FIRST_SEEN}</td></tr>
        <tr><td>Verdict</td><td><span class="tag">${VT_VERDICT}</span></td></tr>
        <tr><td>VT Report</td><td><a href="${VT_LINK}" target="_blank">${VT_LINK}</a></td></tr>
      </table>
    </div>
  </div>

  <!-- SECTION 3 -->
  <div class="section">
    <div class="section-title">SECTION 3 — DYNAMIC ANALYSIS</div>
    <div class="section-body">
      <table>
        <tr><td>Hybrid Analysis</td><td>
          <a href="https://www.hybrid-analysis.com/search?query=${HASH_SHA256}" target="_blank">
          View Sandbox Report</a>
        </td></tr>
      </table>
      <br>
      <strong>IP Addresses &amp; GeoIP:</strong>
      <pre>${GEO_RESULTS:-No external IP addresses detected.}</pre>
    </div>
  </div>

  <!-- SECTION 4 -->
  <div class="section">
    <div class="section-title">SECTION 4 — REMEDIATION ACTIONS</div>
    <div class="section-body">
      <ul class="checklist">
        <li>Isolate the affected machine from the network immediately</li>
        <li>Preserve and back up forensic evidence (disk image, logs)</li>
        <li>Block the sender email address at the mail gateway</li>
        <li>Block identified malicious domains/IPs at the firewall</li>
        <li>Submit sample to AV vendor for signature update</li>
        <li>Scan all machines that may have received the same email</li>
        <li>Reset credentials of any potentially exposed accounts</li>
        <li>Notify management / CISO per incident response policy</li>
        <li>Document all actions with timestamps</li>
        <li>Conduct post-incident review</li>
      </ul>
    </div>
  </div>

  <!-- SECTION 5 -->
  <div class="section">
    <div class="section-title">SECTION 5 — SUMMARY</div>
    <div class="section-body">
      <div class="summary-box">${summary}</div>
    </div>
  </div>

</div>
<div class="footer">Generated by PhishReport &nbsp;|&nbsp; Analyst: ${ANALYST_NAME} &nbsp;|&nbsp; ${SCAN_DATE}</div>
</body>
</html>
HTMLEOF

    echo ""
    echo "[REPORT] ✅ TXT report saved  : $txt_file"
    echo "[REPORT] ✅ HTML report saved : $html_file"

    TXT_REPORT="$txt_file"
    HTML_REPORT="$html_file"
}
